<?php

namespace CSanquer\Bundle\MarkdownBundle\Tests\Highlighter;

use CSanquer\Bundle\MarkdownBundle\Highlighter\Geshi;

class GeshiTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Geshi
     */
    protected $highlighter;

    protected function setUp()
    {
        $this->highlighter = new Geshi();
    }

    public function testColorize()
    {
        $code = <<<PHP
<?php
phpinfo();

PHP
        ;

        $html = <<<HTML
<pre><code class="language-php">//php colorized
&lt;?php
phpinfo();
</code></pre>
HTML
        ;

        $this->assertEquals(
            array(
                'text' => '<ol><li class="li1"><div class="de1"><span class="kw2">&lt;?php</span></div></li><li class="li1"><div class="de1"><a href="http://www.php.net/phpinfo"><span class="kw3">phpinfo</span></a><span class="br0">&#40;</span><span class="br0">&#41;</span><span class="sy0">;</span></div></li><li class="li1"><div class="de1">&nbsp;</div></li></ol>',
                'class' => 'php geshi',
            ), 
            $this->highlighter->colorize($code, 'php')
        );
    }

    public function testGetSupportedLanguages()
    {
        $expected = array(
            '4cs',
            '6502acme',
            '6502kickass',
            '6502tasm',
            '68000devpac',
            'abap',
            'actionscript',
            'actionscript3',
            'ada',
            'algol68',
            'apache',
            'applescript',
            'apt_sources',
            'arm',
            'asm',
            'asp',
            'asymptote',
            'autoconf',
            'autohotkey',
            'autoit',
            'avisynth',
            'awk',
            'bascomavr',
            'bash',
            'basic4gl',
            'bf',
            'bibtex',
            'blitzbasic',
            'bnf',
            'boo',
            'c',
            'c_loadrunner',
            'c_mac',
            'caddcl',
            'cadlisp',
            'cfdg',
            'cfm',
            'chaiscript',
            'cil',
            'clojure',
            'cmake',
            'cobol',
            'coffeescript',
            'cpp',
            'cpp-qt',
            'csharp',
            'css',
            'cuesheet',
            'd',
            'dcl',
            'dcpu16',
            'dcs',
            'delphi',
            'diff',
            'div',
            'dos',
            'dot',
            'e',
            'ecmascript',
            'eiffel',
            'email',
            'epc',
            'erlang',
            'euphoria',
            'f1',
            'falcon',
            'fo',
            'fortran',
            'freebasic',
            'freeswitch',
            'fsharp',
            'gambas',
            'gdb',
            'genero',
            'genie',
            'gettext',
            'glsl',
            'gml',
            'gnuplot',
            'go',
            'groovy',
            'gwbasic',
            'haskell',
            'haxe',
            'hicest',
            'hq9plus',
            'html4strict',
            'html5',
            'icon',
            'idl',
            'ini',
            'inno',
            'intercal',
            'io',
            'j',
            'java',
            'java5',
            'javascript',
            'jquery',
            'kixtart',
            'klonec',
            'klonecpp',
            'latex',
            'lb',
            'ldif',
            'lisp',
            'llvm',
            'locobasic',
            'logtalk',
            'lolcode',
            'lotusformulas',
            'lotusscript',
            'lscript',
            'lsl2',
            'lua',
            'm68k',
            'magiksf',
            'make',
            'mapbasic',
            'matlab',
            'mirc',
            'mmix',
            'modula2',
            'modula3',
            'mpasm',
            'mxml',
            'mysql',
            'nagios',
            'netrexx',
            'newlisp',
            'nsis',
            'oberon2',
            'objc',
            'objeck',
            'ocaml',
            'ocaml-brief',
            'octave',
            'oobas',
            'oorexx',
            'oracle11',
            'oracle8',
            'oxygene',
            'oz',
            'parasail',
            'parigp',
            'pascal',
            'pcre',
            'per',
            'perl',
            'perl6',
            'pf',
            'php',
            'php-brief',
            'pic16',
            'pike',
            'pixelbender',
            'pli',
            'plsql',
            'postgresql',
            'povray',
            'powerbuilder',
            'powershell',
            'proftpd',
            'progress',
            'prolog',
            'properties',
            'providex',
            'purebasic',
            'pycon',
            'pys60',
            'python',
            'q',
            'qbasic',
            'rails',
            'rebol',
            'reg',
            'rexx',
            'robots',
            'rpmspec',
            'rsplus',
            'ruby',
            'sas',
            'scala',
            'scheme',
            'scilab',
            'sdlbasic',
            'smalltalk',
            'smarty',
            'spark',
            'sparql',
            'sql',
            'stonescript',
            'systemverilog',
            'tcl',
            'teraterm',
            'text',
            'thinbasic',
            'tsql',
            'twig',
            'typoscript',
            'unicon',
            'upc',
            'urbi',
            'uscript',
            'vala',
            'vb',
            'vbnet',
            'vedit',
            'verilog',
            'vhdl',
            'vim',
            'visualfoxpro',
            'visualprolog',
            'whitespace',
            'whois',
            'winbatch',
            'xbasic',
            'xml',
            'xorg_conf',
            'xpp',
            'yaml',
            'z80',
            'zxbasic',
        );

        $this->assertEquals($expected, $this->highlighter->getSupportedLanguages());
    }

    public function testCss()
    {
        $this->assertNotEmpty($this->highlighter->getCss());
    }
}
